api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "pfj-cart-transform"
type = "function"
uid = "c2c3c6dc-982e-25f8-f25e-4a18483382149deaa12a"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"